export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const EDITAR_PROYECTO = 'EDITAR_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

export const OBTENER_TAREAS = 'OBTENER_TAREAS';
export const EDITANDO_TAREA = 'EDITANDO_TAREA';
export const TAREA_EDITAR = 'TAREA_EDITAR';
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA';
